### ISSUE TITLE
Some policies are not shown in the tooltip

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#103]
![image](https://user-images.githubusercontent.com/14053728/86583058-4e1b6900-bf8b-11ea-84eb-609cf9ca8c72.png)
Despite the fact I have this policy and work item linked to the PR:
![image](https://user-images.githubusercontent.com/14053728/86583090-5a072b00-bf8b-11ea-830c-7cc6775b6e75.png)

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/87282546-0ea9cb00-c4fd-11ea-8db9-ee61c3041354.png)
![image](https://user-images.githubusercontent.com/14053728/87282640-25e8b880-c4fd-11ea-9782-1d63eb9faa13.png)
![image](https://user-images.githubusercontent.com/14053728/87282649-297c3f80-c4fd-11ea-89ce-9a2484dc4db3.png)

**Comment by cribeiro84** [comment]
Is it still happening?

**Comment by vladkasianenko** [comment]
Yes.
