### ISSUE TITLE
Invalid counter of reviewers

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#104]
So, we have a branch policy to include at least 1 review of the PR.
But at the PR level, I can set up required and optional reviewers.
Then, the logic should be like this:
``` typescript
var branchPolicyMinimumApproversCount: number;
var pullRequestRequiredApproversCount: number;
var tooltipReviewers: number =
pullRequestRequiredApproversCount > branchPolicyMinimumApproversCount
? pullRequestRequiredApproversCount
: branchPolicyMinimumApproversCount;
var tooltipReviewersApproved: number;
```
![image](https://user-images.githubusercontent.com/14053728/86583805-87080d80-bf8c-11ea-8891-e4e537317629.png)
![image](https://user-images.githubusercontent.com/14053728/86583818-8a9b9480-bf8c-11ea-9cd3-df6a9713b68d.png)
Does it sound logical?

**Comment by cribeiro84** [comment]
@vladkasianenko thanks for bringing this up. To be honest I don't consider this as an issue because two persons have approved and based on your policy and message: 2 approves have been given where it would require only one.
