### ISSUE TITLE
Layout broken for long items

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#105]
![image](https://user-images.githubusercontent.com/14053728/86584167-2e854000-bf8d-11ea-8cfa-6826fc38a8a6.png)

**Comment by vladkasianenko** [comment]
It was OK on the 4K, but on the simple laptop, it is not well-fitted.

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/88783151-1fae3980-d197-11ea-986d-9be4c928b9b0.png)

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/88785662-28ecd580-d19a-11ea-8ba7-d3c2f3f6ba29.png)
Different spaces between these items.

**Comment by cribeiro84** [comment]
Work in progress :-)
We decided to remove the "last commit ID" and to introduce a smaller icon for "Linked Work Items". It will be available very soon.
