### ISSUE TITLE
Suggestion: when all required approvers approved - mark badge as green

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#106]
![image](https://user-images.githubusercontent.com/14053728/86609078-14128d00-bfb4-11ea-9213-08175433fc30.png)
I guess it's gonna be cool to have a green badge when all required approvers approved the PR. Maybe adding a green check will be a good idea as well.
What do you think?

**Comment by cribeiro84** [comment]
The badge goes away whenever the required review is no longer needed. Therefore, we will not work on this.
