### ISSUE TITLE
Highlight required approvers

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#107]
I guess it should be some kind of "*" or something with the approver's image to identify them as required.

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/86610041-73bd6800-bfb5-11ea-9a48-6f44e469ed06.png)
Maybe something like this. Note that some approvers have circle in the color of the state.

**Comment by cribeiro84** [comment]
It's in progress:

![image](https://user-images.githubusercontent.com/328635/86984748-d0f81b80-c165-11ea-8b02-2b0eb6ef01c2.png)

I will try to add other improvements on the same new version to be released soon.

**Comment by vladkasianenko** [comment]
What to do if the person doesn't have any photo?
![image](https://user-images.githubusercontent.com/14053728/87039151-6c859c80-c1f7-11ea-871e-b075972db959.png)
For the status circle, it might some kind of shadow, maybe.
