### ISSUE TITLE
Tooltip VSSPerson is centered

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#108]
Shouldn't it be left-aligned?
![image](https://user-images.githubusercontent.com/14053728/86784517-47afee80-c06a-11ea-8a22-b8a1dea1c64d.png)

**Comment by cribeiro84** [comment]
Is this happening in which browser? I was not able to simulate it on Firefox, Chrome or Safari.

**Comment by vladkasianenko** [comment]
Version 83.0.478.61 (Official build) (64-bit)
![image](https://user-images.githubusercontent.com/14053728/87018892-954b6900-c1da-11ea-9d84-caaa2449a295.png)

**Comment by vladkasianenko** [comment]
Plus, I guess it makes sense to add a badge for the required reviewer in the tooltip.
