### ISSUE TITLE
All reviewers are marked as Required, but they are not

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#111]
![image](https://user-images.githubusercontent.com/14053728/87281380-d655bd00-c4fb-11ea-89c2-4214c08a8a27.png)
![image](https://user-images.githubusercontent.com/14053728/87281399-d9e94400-c4fb-11ea-91ed-562c35810c42.png)

**Comment by cribeiro84** [comment]
The extension shows all reviewers added to the PR regardless if it's required or not. Perhaps, instead of removing the optional, we can find a way to show it as a lighter circles.

**Comment by vladkasianenko** [comment]
It makes no sense for me to circle both required and optional reviewers. So we need to find a way only to circle required and not to circle optional. What do you think?

**Comment by cribeiro84** [comment]
I believe I've found the issue and I will try to work on that this week. It seems the some cases the isRequired attribute is not coming and perhaps it's probably breaking the validation to check if it's required or optional. About the listing the Reviewers, I don't think we should touch on that, we just need to identify why it's understanding as "Required" when it"s optional.

**Comment by vladkasianenko** [comment]
I still have this issue.

**Comment by cribeiro84** [comment]
I was able to simulate the issue and now for me it's gone. Are them just optional on your PR or is there any additional policy to it?

**Comment by vladkasianenko** [comment]
Yes, all of them are optional.

**Comment by cribeiro84** [comment]
@vladkasianenko - I'm still not able to simulate the issue. When I was able to, I've added all members as optional and since the last version it's working fine. Do you have additional steps to simulate it?

**Comment by vladkasianenko** [comment]
No, I don't have other steps.
In my case they are all optional.
![image](https://user-images.githubusercontent.com/14053728/88786219-ec6da980-d19a-11ea-8d56-a7263da6e79b.png)
