### ISSUE TITLE
Invalid status

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#112]
![image](https://user-images.githubusercontent.com/14053728/87281491-f5ece580-c4fb-11ea-88f7-3850c7c77f73.png)
As you can see, all checks are ok and no required reviewers.
But at the dashboard:
![image](https://user-images.githubusercontent.com/14053728/87281549-02713e00-c4fc-11ea-9379-bde65b3a3e70.png)

**Comment by vladkasianenko** [comment]
Plus, circle status and policies are not in the sync.

**Comment by cribeiro84** [comment]
#111 duplicated
