### ISSUE TITLE
When clicking on a pull request, the redirect goes via wrong url

### ISSUE THREAD

**Issue by PaulKamps** [cribeiro84/azure-devops-pull-request-hub#116]
When I click a PR the redirect goes to https://caribeiro84.gallerycdn.vsassets.io/extensions/Project/Repo.
This is weird because it leave the azure devops environment.

**Comment by cribeiro84** [comment]
Thanks for the feedback @PaulKamps - I'm not able to simulate the issue. Are you using the ADO Cloud or Server? Have you tried to clear you browser cache?

Thanks

**Comment by PaulKamps** [comment]
I'm using FireFox with the following Smart Referer. This addon removes redirects and your plugin redirects the pull request to https://caribeiro84.gallerycdn.vsassets.io.

**Comment by cribeiro84** [comment]
Yes, the plug-in required to change the URL because it's by design of all extensions of ADO. I'm not able to fix it.
