### ISSUE TITLE
Filtering repositories not working after Refresh

### ISSUE THREAD

**Issue by iPiTe** [cribeiro84/azure-devops-pull-request-hub#117]
We have several repos in our project. If we filter some repos, after refresh we still see all repos , although they seem 
to be filtered when clicking the filter button. 
Once you check \ uncheck the repo , it's filtered till the next time you refresh. 
(this behavior start couple of days ago, maybe something in the latest changes ? )

**Comment by dennisroche** [comment]
also noticed this issue. looks like filtering was changed recently in https://github.com/cribeiro84/azure-devops-pull-request-hub/pull/110.

**Comment by cribeiro84** [comment]
Sorry about this issue, the new version I'm releasing in a few minutes fixes the issue. :-)

**Comment by dennisroche** [comment]
thanks @cribeiro84. it's a great extension 👍

**Comment by cribeiro84** [comment]
Thanks a lot for your feedback @dennisroche ;-)
Don't forget to rate our extension in the marketplace in case you didn't yet... :-)

**Comment by iPiTe** [comment]
Thanks @cribeiro84 for the quick fix . 
Totally agree with @dennisroche :) Our Team here just love it, helps us a lot managing PR's for 10 Repo's with ease.
