### ISSUE TITLE
REST API version of 5.2 is out of range for this server.

### ISSUE THREAD

**Issue by hwoodward2019** [cribeiro84/azure-devops-pull-request-hub#118]
As of 7/15/2020, We are still experiencing the same issue regarding "TFS.WebApi.Exception: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1."

I see in your notes, that you are downgrading the API due to Azure DevOps server issues. Is this still happening? I seen that an update was pushed yesterday and the team is still receiving the error. Any update would be appreciated, I assuming you are still working the issue and I am just being impatient :) On a side note, thank you for your hard work!

_Originally posted by @hwoodward2019 in https://github.com/cribeiro84/azure-devops-pull-request-hub/issues/113#issuecomment-658782609_

**Comment by purduekenny** [comment]
I will second that the issue is persisting as of your v1.20200713.1 released about 7 hours ago.

**Comment by craigeddy** [comment]
Same here ... v1.20200713.1 not working in on-prem 2019 Version Dev17.M153.4

**Comment by cribeiro84** [comment]
I've found the issue which was causing it and I hope the new version I'm releasing in a few minutes fixes it.
