### ISSUE TITLE
Table rows flickering (constantly updating) for 4-6 seconds on refresh 

### ISSUE THREAD

**Issue by dennisroche** [cribeiro84/azure-devops-pull-request-hub#123]
Appears to be rows that are outside/on the edge of the scroll view. Noticed this with 24+ PRs open and likely not to happen with smaller list as not being virtualised.

Unable to share a video/image of issue as too much info to sensor :)

Happy to pick this up and raise a PR if you don't have the time.

**Comment by cribeiro84** [comment]
Hello @dennisroche 
thanks for the feedback. I noticed it also after my recents changes that I was trying to improve the status sync between policies, reviewers, so on. There are several additional APIs that must be called asynchronously to enrich the PR model that's returned from the original API (Get Pull Request). I'll be very glad if you want to take this up to fix it

Thank you very much.

**Comment by cribeiro84** [comment]
@dennisroche - We fixed the issue! Please check from your side. :-)

Also don't forget to rate our extension in case you didn't yet ;-)
