### ISSUE TITLE
Black blinking pointer is almost invisible

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#125]
The black blinking pointer is almost invisible for the search box. Have a look:
![image](https://user-images.githubusercontent.com/14053728/87876381-82a61080-c9e0-11ea-881a-78045bb9261a.png)
For comparison, have a look at the top search box with a white blinking pointer:
![image](https://user-images.githubusercontent.com/14053728/87876392-96517700-c9e0-11ea-93ea-aec667edb906.png)

**Comment by cribeiro84** [comment]
I was not able to identify where it`s causing this issue. There is no place in the code where we manually set the black color to the text. It seems to be a bug in the ADO css. I will try to find a workaround for it.
