### ISSUE TITLE
If no Pullrequests are active it loads forever

### ISSUE THREAD

**Issue by maltevesper** [cribeiro84/azure-devops-pull-request-hub#126]
If a project has no active pull requests the loading spinner won't disappear.

Due to this I thought the extension was broken when we installed it on our production server. A message that there are currently 0 open Pull Requests would be nice.

I assume that this is a general issue, nevertheless this was tested with the following version:

Installed version
1.20200716.1 (Latest)
Last updated
Jul 17, 2020 at 9:04 PM GMT+2

Running on (presumably, not sure how to find out as a non Admin): Azure Devops 2019 (on premisis)

**Comment by cribeiro84** [comment]
@maltevesper - Would you please check it the problem is solved? We did a recent fix and we identified where it was causing.

Please also, in case you did not do yet, rate our extension in the marketplace of ADO :-)

**Comment by maltevesper** [comment]
@cribeiro84 It is fixed, thanks. I jsut headed over to the marketplace to rate it, but could not find an option to rate it. I am afraid I mgiht not be allowed to rate it as a tfs user and not an admin?

**Comment by cribeiro84** [comment]
Thanks a lot @maltevesper for the feedback and I'm glad it's now fixed. About the rating, please find below the URL:
https://marketplace.visualstudio.com/items?itemName=caribeiro84.pull-request-manager-hub&ssr=false#review-details

Thanks a lot
