### ISSUE TITLE
[Idea] Implementation of quick filter for reviewers

### ISSUE THREAD

**Issue by jonatancompiani** [cribeiro84/azure-devops-pull-request-hub#128]
Having an option to show only the relevant PRs for the review. (similar to a filter by PR status)
For instance, showing only the PRs that are not ready to complete, or that **I am** waiting for author.

By doing so, I don't need to see:
- PRs that are waiting for author by other reviewers   
- PRs that have been already approved
- PRs that are in failure status

With the new feature of saving filters, me, as a reviewer, could just access the screen and see the relevant items on one filter.

**Comment by cribeiro84** [comment]
@jonatancompiani - just one of the "Quick Filters" that's not available yet. For the Approved PRs and Failure Status you can use the Alternate Status option to select them.
