### ISSUE TITLE
UI Changes - Too many things are highlighted

### ISSUE THREAD

**Issue by jonatancompiani** [cribeiro84/azure-devops-pull-request-hub#130]
Small suggestions to make the screen look less cluttered

![image](https://user-images.githubusercontent.com/15322453/88394409-c9f02080-cd95-11ea-9106-00b14ec8fe7b.png)

**Comment by vladkasianenko** [comment]
The border around image is used for the required reviewers.

**Comment by jonatancompiani** [comment]
Oh, cool. I didn't know that.
I'm wondering, should we display the optional reviewers at all? Is it useful in some scenario?
Maybe create a configuration for displaying it.
