### ISSUE TITLE
View of recently completed pull requests

### ISSUE THREAD

**Issue by maltevesper** [cribeiro84/azure-devops-pull-request-hub#131]
Enhancement request:

It would be nice to have a tab with recently completed pull requests, so one can follow what has changed recently, especially if PRs get completed before one sees them. A fork of this, also found on the marketplace, does this nicely in a seperate tab.

**Comment by cribeiro84** [comment]
Thanks @maltevesper for the request. The Completed PRs tab is in progress and will be available very soon alongside with some additional enhancements.
