### ISSUE TITLE
Circle color is not corresponds to the Review Status

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#135]
![image](https://user-images.githubusercontent.com/14053728/88785919-7ec17d80-d19a-11ea-979f-9663e1b253ea.png)
First and third circles should be orange, shouldn't they?

**Comment by cribeiro84** [comment]
I was not able to simulate the issue. It's really strange that's happening because the icon uses the same function to circle the avatars. The reviewers are waiting for author, right? Therefore, it should both avatars with orange circle. Is it right?

**Comment by cribeiro84** [comment]
Hi @vladkasianenko 
is this still happening?

**Comment by cribeiro84** [comment]
I was able to reproduce the bug and it seems to be a cache issue during the render process of the Table component. If you just refresh the results (refresh button), the status color is restored properly. I will check of hypothesis that came up to my mind that could solve the issue.
