### ISSUE TITLE
visual studio 2019

### ISSUE THREAD

**Issue by monsieurbond** [cribeiro84/azure-devops-pull-request-hub#149]
Apparently it does not support visual studio 2019 professional

Cheers from Mexico
[dd_VSIXInstaller_20200824110933_4924.log](https://github.com/cribeiro84/azure-devops-pull-request-hub/files/5119010/dd_VSIXInstaller_20200824110933_4924.log)

**Comment by cribeiro84** [comment]
Hello @monsieurbond - thanks for the feedback but I'm not sure if I get it. Did you try to install the extension on VS2019? This extension is not meant for that. The extension is meant to be installed on Azure DevOps Services (or Server).

**Comment by monsieurbond** [comment]
Oh! That is the problem haha, well, thanks for you feedback my friend, have a good day.

Seguimos a sus órdenes.
[rsz_eden]<http://www.edenred.com/>


Ing. Jorge Olvera
Desarrollador | Medios de Pago
Edenred
Lago Rodolfo 29,
Col. Granada, C.P.11520,
Ciudad de México.
[cid:image003.png@01D67A0B.5E9DD800]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_edenredmexico-3Flang-3Des&d=DwMFAw&c=O17m6UdqOAIZh9XQ8pTl4g&r=f9CI2LPMOCYk5Rg6dYzKKrA175-BfViHnBFXBCLhNWo&m=kiX64tiZwNjeaOrCrfxma_wgCb-AeTtxa1XJcAFumTg&s=zeBzgvA_MRSA88diE1_ovETbJT3gRAujRIGRTAOMUU0&e=>
[cid:image004.png@01D67A0B.5E9DD800]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company-2Dbeta_809142_&d=DwMFAw&c=O17m6UdqOAIZh9XQ8pTl4g&r=f9CI2LPMOCYk5Rg6dYzKKrA175-BfViHnBFXBCLhNWo&m=kiX64tiZwNjeaOrCrfxma_wgCb-AeTtxa1XJcAFumTg&s=C7AK7czweexWFjXcz1lCwoxOY1q3UUIOwZ1xgN9Qhac&e=>
[cid:image005.png@01D67A0B.5E9DD800]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.youtube.com_user_EdenredMX&d=DwMFAw&c=O17m6UdqOAIZh9XQ8pTl4g&r=f9CI2LPMOCYk5Rg6dYzKKrA175-BfViHnBFXBCLhNWo&m=kiX64tiZwNjeaOrCrfxma_wgCb-AeTtxa1XJcAFumTg&s=oEYud7r8RMzooDH7nY4DANubnThUfqEjz0TCTiFizFY&e=>
[cid:image006.png@01D67A0B.5E9DD800]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.instagram.com_EDENRED_&d=DwMFAw&c=O17m6UdqOAIZh9XQ8pTl4g&r=f9CI2LPMOCYk5Rg6dYzKKrA175-BfViHnBFXBCLhNWo&m=kiX64tiZwNjeaOrCrfxma_wgCb-AeTtxa1XJcAFumTg&s=zyNwwmeRzCdogwZuLAb43VJIIjA9RjJkVOsHc78LPo8&e=>
[cid:image007.png@01D67A0B.5E9DD800]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_EdenredMx_&d=DwMFAw&c=O17m6UdqOAIZh9XQ8pTl4g&r=f9CI2LPMOCYk5Rg6dYzKKrA175-BfViHnBFXBCLhNWo&m=kiX64tiZwNjeaOrCrfxma_wgCb-AeTtxa1XJcAFumTg&s=9NxaM2dk-vnkBwjq8TVYen_ZqNKp_iU5xyWuBPoz2ug&e=>

**Comment by cribeiro84** [comment]
You are welcome, @monsieurbond! I'm closing the issue then.
