### ISSUE TITLE
Buttons to navigate to a PR does not work

### ISSUE THREAD

**Issue by philippedurocher** [cribeiro84/azure-devops-pull-request-hub#150]
When I try to click the link button to navigate to a Pull Request, nothing happen.

There is a space in my Team Project name.

**Comment by cribeiro84** [comment]
Hi @philippedurocher 
Would you mind to check on the Console tab of Developer Tools (F12) of your browser to check if there is any error there? The tem Project Name shouldn't impact on that..

**Comment by philippedurocher** [comment]
I don't have an error when I click the link but I see some errors when load the page 

![image](https://user-images.githubusercontent.com/1459389/91983280-71e3fc80-ecf9-11ea-87c6-a026bd8d477e.png)

**Comment by cribeiro84** [comment]
Thanks for sharing the details @philippedurocher. I see that you are using the old ADO URL scheme. Would you mind to test using the new? It will look like:

https://dev.azure.com/{YOUR_ORG_ACCOUNT}

**Comment by philippedurocher** [comment]
![image](https://user-images.githubusercontent.com/1459389/91998471-3bae7900-ed09-11ea-9bf6-73d3d7e16f52.png)

I'm using the new URL to login but I did not change the URL in org settings.

Seems the profile images still uses the old URL.

**Comment by cribeiro84** [comment]
@philippedurocher thanks for sharing the details. It's the first time I see this issue happening.
Would you mind to once again check in our Org's Settings if is it using the new URL format?

![image](https://user-images.githubusercontent.com/328635/91999753-1de61180-ed13-11ea-965b-f89f8fc3ae6a.png)

**Comment by philippedurocher** [comment]
![image](https://user-images.githubusercontent.com/1459389/92001853-34896a00-ed0d-11ea-867c-07bb94c371b5.png)

Now images are using new URL but still buttons not working.

**Comment by philippedurocher** [comment]
I decided to uninstall and reinstall the extension with new URL.

Now base URL reference and base URL are good. But buttons still not working.

![image](https://user-images.githubusercontent.com/1459389/92005645-b5e2fb80-ed11-11ea-8de7-364f3a234a36.png)

**Comment by cribeiro84** [comment]
That's really really strange! Once more question from my end. Could you please check if the pop-up is blocked? The extension tries to open a new window when you click on it.

**Comment by cribeiro84** [comment]
I'm glad it's fixed :-)
You can set your preferences also to make it to open on the same window, if you prefer. ;-)

**Comment by cribeiro84** [comment]
Hi @philippedurocher - please don't forget to give your rating to the extension in the marketplace, it helps us to improve it :-)
