### ISSUE TITLE
PR Links Using Old URL Format

### ISSUE THREAD

**Issue by kyleherzog** [cribeiro84/azure-devops-pull-request-hub#151]
The links to the PRs link to the old DevOps URL format.  (https://[account].visualstudio.com/)

1. Go to https://dev.azure.com/[account]/AS/_apps/hub/caribeiro84.pull-request-manager-hub.view
2. Click on any PR name link
3. New browser window opens up in https://[account].visualstudio.com/ format.

**Expected behavior**
The new window that opens up should be in the new format (https://dev.azure.com/[account]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 84

**Comment by cribeiro84** [comment]
Hello @kyleherzog 
Thanks for the inputs. The extension is based on the primary URL set on the Org's settings where it's being used the old or new URL scheme. Could you please confirm which one is it set for your account?

Thanks a lot

**Comment by kyleherzog** [comment]
Didn't know that setting existed. That fixed it. Thanks!

**Comment by cribeiro84** [comment]
You are welcome @kyleherzog - don't forget to give your rating to the extension in the marketplace, it helps us to improve it :-)
