### ISSUE TITLE
New update icon appears when I approve a PR

### ISSUE THREAD

**Issue by jonatancompiani** [cribeiro84/azure-devops-pull-request-hub#156]
Whenever I approve a PR, when I come back to the manager hub and I see the new updates blue indicator.
![image](https://user-images.githubusercontent.com/15322453/93233756-d53a4980-f751-11ea-855b-ffc1df406276.png)

By entering in the PR, I see the last update was my own approval.
![image](https://user-images.githubusercontent.com/15322453/93233890-fe5ada00-f751-11ea-9267-389d82ef8b16.png)

**Comment by cribeiro84** [comment]
It creates an event that updates your PR and we capture that.
