### ISSUE TITLE
"Top Completed/Abandoned PRs" setting has no effect

### ISSUE THREAD

**Issue by jbingham90** [cribeiro84/azure-devops-pull-request-hub#161]
**Describe the bug**
When I go to the "Recently Completed" and "Recently Abandoned" tabs, the entire history of all pull requests for all repositories is displayed. We have ~400 repositories and ~15,000 completed pull requests, so the content never finishes loading and the view is frozen until I completely reload the page. However, the "Top Completed/Abandoned PRs" setting seems to indicate those views should only be loading the most recent 25 pull requests (if I understand that setting correctly).

**To Reproduce**
1. Go to Pull Request Manager Hub in an Azure DevOps account that has many repositories and many pull requests.
2. Click on "Recently Completed" or "Recently Abandoned"

**Expected behavior**
If I'm understanding the purpose of the "Top Completed/Abandoned PRs" setting, when 25 is entered, only 25 items should be displayed on the "Recently Completed" and "Recently Abandoned" tabs. If that's not what the setting means, then a setting that limits the default number of items that display on those views (either by count or by date range -- i.e., the past month) would make those views usable when there is a large history of pull requests.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.198

**Additional context**

**Comment by cribeiro84** [comment]
Hello @jbingham90 - thanks for raising this issue. However, I'm afraid this is not an issue because this feature is meant to limit how many PRs will be fetched for each repo you have. You can change the max number in Preferences but because you have so many repos, it will still be slow once the extension needs to call the APIs several times.
