### ISSUE TITLE
There was an error during the extension load: TFS.WebApi.Exception: TF401027

### ISSUE THREAD

**Issue by robduncan-novia** [cribeiro84/azure-devops-pull-request-hub#165]
**Describe the bug**
[https://github.com/cribeiro84/azure-devops-pull-request-hub/issues/96](https://github.com/cribeiro84/azure-devops-pull-request-hub/issues/96) is still an issue

**To Reproduce**
Installed plugin and accessed for the first time

**Expected behavior**
See open PR's

**Screenshots**
![image](https://user-images.githubusercontent.com/69814868/106177589-9f41b300-6190-11eb-88e1-b54ca79dd695.png)

**Additional context**
I have admin access but can't find that repo.  Please change the code to ignore repos with no read permission.  We have to uninstall this now until this is fixed.

**Comment by UnaffiliatedCode** [comment]
I can confirm that this has been an ongoing problem in our Azure DevOps environment. Currently impacts all users.
My the referenced identity is full admin in the target repository(s).

![image](https://user-images.githubusercontent.com/56409830/106638994-7c2d4f80-6552-11eb-8551-b90bc4c41675.png)

In this instance, either the referenced identity used is incorrect, or the error message is incorrect in another manner. This issue has halted our usage of the extension until it can be resolved.

**Comment by tbertenshaw** [comment]
Can confirm I am also experiencing this error.

**Comment by cribeiro84** [comment]
Hello @tbertenshaw @UnaffiliatedCode @robduncan-novia - the permissions are not handled by our extension we just fetch all repositories the API retrieves to our extension. There is no option to set any filter to ignore repos you don't have access to or at least we didn't find any. We will investigate it further but I'm not sure if we will be able to fix it.

**Comment by cribeiro84** [comment]
#170 related to. Please take a look on the workaround mentioned in the other issue.

Thanks
