### ISSUE TITLE
switching from dev.azure.com/org to org.visualstudio.com

### ISSUE THREAD

**Issue by hvkooten** [cribeiro84/azure-devops-pull-request-hub#166]
I use https://dev.azure.com/org as URL for Azure Devops. When I click on  a pull request link in the Pull Request Manager Hub, I am redirected to org.visualstudio.com

Could you fix this?

**Comment by cribeiro84** [comment]
Hello @hvkooten, thanks for raising this issue. I believe the issue is related to your Org configuration where it's not set to use the new URL format which we capture from an available API from Azure DevOps APIs. Can you check that?

Thanks

**Comment by hvkooten** [comment]
You are correct. That option is not enabled. 👍
