### ISSUE TITLE
The extension does not load, no PRs are shown when an older filter is present 

### ISSUE THREAD

**Issue by nemesmia-gm** [cribeiro84/azure-devops-pull-request-hub#169]
The extension does not load; it shows for a very short time the head line and then the page is blank.

I have this behaviour since last year. 
I've created at some time a filter and then update the extension.
After the update the extension does not work for me anymore. 
Other people in the team can use it, I think they don't have used the filters

1. Click on the extension in Azure DevOps
2. The page loads and displays for 1 second the headline, then the page is blank

**Expected behavior**
The page shows all the PRs.

**Desktop**
 - OS: Windows
 - Browser: chrome

It works on Firefox.

**Comment by cribeiro84** [comment]
Thanks @nemesmia-gm for raising this issue. Could you please check on your Console tab of your browser if there is any error? It looks like permission issue.

**Comment by nemesmia-gm** [comment]
I see many errors, one of them is:Access to fetch at 'https://dev.azure.com/...........' from origin 'https://caribeiro84.gallerycdn.vsassets.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by nemesmia-gm** [comment]
This one is another: No permissions found for security namespace 'someGuid' and token 'repoV2/some Guids'. Ensure that the effective permissions are included in shared data. I'm not sure if it is releated to

**Comment by nemesmia-gm** [comment]
and one more:  Failed to load resource: the server responded with a status of 404 https://storage.live.com/Users/GUID/MyProfile/ExpressionProfile/ProfilePhoto:Win8Static,UserTileMedium,UserTileStatic/MeControlXXLUserTile?ck=1&ex=24  also not sure if it is related

**Comment by cribeiro84** [comment]
This CORS issue might be related to Azure DevOps itself because the extension is fully hosted by ADO in a different domain. Do you have any browser extension that could be blocking that also?

**Comment by nemesmia-gm** [comment]
I've disabled all the browser extensions and it doesn't help.

Starting chrome like this from cmd works:
start chrome --disable-web-security --disable-gpu --user-data-dir=~/chromeTemp 

I think it is related to chrome, and it's not an issue of an extension.
