### ISSUE TITLE
My Pull Requests Filter

### ISSUE THREAD

**Issue by agilenut** [cribeiro84/azure-devops-pull-request-hub#177]
I would like to be able to view Pull requests that are assigned to me and that I have created. Currently, this requires 2 different filters. A simple, My stuff filter would be nice or perhaps the option to save more complex filters that use OR instead of AND.

It would be even better if I could group them visually by the PRs that are created by me vs. the ones that I'm reviewing.

**Comment by cribeiro84** [comment]
#155 - duplicated
