### ISSUE TITLE
[Bug] On premise error `Ensure that the effective permissions are included in shared data.`

### ISSUE THREAD

**Issue by Herve-M** [cribeiro84/azure-devops-pull-request-hub#180]
**Describe the bug**
After installing the extension, going to the hub show nothing. 
Only `Projects` list is fetched correctly, `Repositories` is empty.

**To Reproduce**
1. Install the extension
2. Go to `Pull Request Manager Hub`

**Expected behavior**
List of PRs. 

**Screenshots**
(won't really help)
![image](https://user-images.githubusercontent.com/1846023/113557419-2e06fc00-9628-11eb-82ff-e7da8fd71c32.png)

**Desktop:**
 - OS: Windows 10 Pro 2004
 - Browser: Edge 89.0.774.63 (Official build) (64-bit)

**Azure DevOps**
- Type: On premise
- Version: 2020 Dev18.M170.6 (18.170.30525)
- Auth type: basic
- Extension version: 2.20210403.1

**Additional context**
Console logs: 
- `Failed to set referrer policy: A policy specified by a meta element must contain only one token. The referrer policy has been left unchanged.` VM3009 {PrjectName}:formatted
- `ms.vss-web.platform-content.es6.T1WfB1Bq6sDuC5Cr.min.js:1 No permissions found for security namespace '2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87' and token 'repoV2/98bddb60-ddf8-4e5f-ab96-7a05c94ae30d/4c58260d-5440-4934-965a-838f34ef241a/'. Ensure that the effective permissions are included in shared data.` ms.vss-web.platform-content.es6.T1WfB1Bq6sDuC5Cr.min.js:formatted at L4555
- `Failed to load resource: the server responded with a status of 404 (Not Found)` targeting: `https://something.com/tfs/_apis/public/gallery/publisher/caribeiro84/extension/pull-request-manager-hub/2.20210403.1/assetbyname/build/[object%20Module]`

**Comment by cribeiro84** [comment]
Hi @Herve-M 
Do you have any disabled repo? If so, try to Re-enable it again to check if the issues goes away. I've released this new version to fix this issue but it seems for OnPrem it didn't work. Please confirm if the above approach works.

Thanks a lot

**Comment by InKahootz** [comment]
We do not have any disabled repos and are seeing the same issue.

**Comment by agileramblings** [comment]
We are also having the same issue this morning. There is no way to roll back to a previous version of the extension either, so we have currently uninstalled this extension. :(

**Comment by cribeiro84** [comment]
It's not clear for me what's the error itself. Those errors you mentioned seems to be an issue to load resources that drives me to an assumption of browser cache. Would you be able to clear the cache of your browser or try with Private Tab?
If you could provide more details (if exists) in the console tab from your developer tools (F12) window would be great.

**Comment by cribeiro84** [comment]
> @cribeiro84
> We are seeing the same issue this morning. When you say disabled repo, you mean _any_ project that has this feature disabled?
> ![image](https://user-images.githubusercontent.com/1909698/113580427-b7500b80-95f3-11eb-8bda-a00ecd484b66.png)
> 
> We do have one project with that flag disabled. I re-enabled it but it didn't have any effect on the issue.

About this disabled repo, I meant in the Repositories management where you can disable an individual repo, like:

![image](https://user-images.githubusercontent.com/328635/113592782-fab67400-960b-11eb-9c17-fe92d1cf53a6.png)

**Comment by agileramblings** [comment]
@cribeiro84 You cannot disable repositories on-prem. (At least I cannot find a way)

![image](https://user-images.githubusercontent.com/9729653/113613024-d9568780-960d-11eb-8bc8-029a576929a1.png)

Using Private Window in Firefox has no effect on the outcome.

![image](https://user-images.githubusercontent.com/9729653/113613170-0c991680-960e-11eb-8dd9-547888f315b7.png)

Some PRs are listed in the PR tab

![image](https://user-images.githubusercontent.com/9729653/113613265-35b9a700-960e-11eb-9864-cb59c805c5e9.png)

**Comment by agileramblings** [comment]
@cribeiro84 Repositories list in the filter is empty

![image](https://user-images.githubusercontent.com/9729653/113613479-87fac800-960e-11eb-80b4-1033b79535ea.png)

**Comment by cribeiro84** [comment]
Thanks for sharing more details. Would you be able to take a screenshot or to capture the console log entries (errors and logs)? Unfortunately, I don't have an OnPrem instance to test it.

**Comment by agileramblings** [comment]
![image](https://user-images.githubusercontent.com/9729653/113613698-d314db00-960e-11eb-983a-3c5a57c9b1db.png)

**Comment by cribeiro84** [comment]
> @cribeiro84 Repositories list in the filter is empty
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/9729653/113613479-87fac800-960e-11eb-80b4-1033b79535ea.png)
> 
> 

Is there a way for you to check on the Network tab the request to "Repositories" API? It should end like: /_apis/git/Repositories?includeLinks=true

**Comment by agileramblings** [comment]
![image](https://user-images.githubusercontent.com/9729653/113614037-33a41800-960f-11eb-9e0d-50e8a6141e8f.png)

**Comment by InKahootz** [comment]
> Is there a way for you to check on the Network tab the request to "Repositories" API? It should end like: /_apis/git/Repositories?includeLinks=true

The response looks good on my side too. The json contains all the repos of the currently selected projects in the filter. However, I'm unable to change the project filters. After clicking a checkbox or two, you get this in the console:

![image](https://user-images.githubusercontent.com/1909698/113618689-06af2f80-9626-11eb-9722-e32d3d156da4.png)

**Comment by agileramblings** [comment]
Our repository data is also present/listed in the `200` response from the GET /git/Repositories call.

**Comment by agileramblings** [comment]
![image](https://user-images.githubusercontent.com/9729653/113621837-63581d80-9619-11eb-9f56-4e58c2697bd8.png)

**Comment by cribeiro84** [comment]
I don't think the problem is this 404 object/error because the APIs are being called and it's getting the results. This asset error might be related to an image for No PRs screen which is not being found. 

It's not clear why the result is not being well handled. Do you have more than 1 project within the same instance? If so, are you able to select different project?

**Comment by agileramblings** [comment]
We only have one active TeamProject (it is the only one with PRs) but we have 3 other TeamProjects in the TPC and they do show up in the Projects filter list.

**Comment by cribeiro84** [comment]
Got it! Just one thing that came up to my mind. Can you check if in the response from Repositories API call if there is an attribute called "isDisabled" that should be equal to false? I indeed did a change in the last release that could've broken for you in case this attribute doesn't exist at all in OnPrem versions.

**Comment by agileramblings** [comment]
![image](https://user-images.githubusercontent.com/9729653/113629307-7bcd3580-9623-11eb-8808-56ef15dc2763.png)
There is a list of [object] that I've expanded one example of. Each [Object] seems to be a repository list item. There is no property on the list item of "isDisabled" that I can find.

**Comment by InKahootz** [comment]
I'm not seeing the field either on my onPrem environment.

![image](https://user-images.githubusercontent.com/1909698/113631490-8db8d380-9637-11eb-9839-3b17ba9b0c9a.png)

Here's the response from my personal Azure Devops Services

![image](https://user-images.githubusercontent.com/1909698/113632823-d6718c00-9639-11eb-8b3f-b0c13474c24b.png)

**Comment by cribeiro84** [comment]
I just released a new version with a possible fix. Can you try again to use the extension?

**Comment by agileramblings** [comment]
![image](https://user-images.githubusercontent.com/9729653/113648766-67e8fa00-964a-11eb-896b-77b746e6b9ed.png)

:(

![image](https://user-images.githubusercontent.com/9729653/113648817-7a633380-964a-11eb-8c03-e846618b7f52.png)

**Comment by cribeiro84** [comment]
Would you be able to fork/checkout this repo and debug from your OnPrem instance? I can assign you to a dev/test extension I have for development purposes to allow you to debug it. I would need your account/org name.

**Comment by Herve-M** [comment]
@cribeiro84 Sadly as agileramblings said, OnPremise don't have the feature of disabling a repository yet. 

Questions: 
* I don't see any [contribution ](https://docs.microsoft.com/en-us/azure/devops/extend/develop/contributions-overview?view=azure-devops) in the manifest, maybe it could lead to permission problems?
* I found this [issue](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6328) ([stack](https://stackoverflow.com/questions/63666441/no-permissions-found-for-security-namespace-while-develop-extension-for-sure-dev)) but no real fix.

**Comment by InKahootz** [comment]
I got it debugging. Your instructions in the README were very helpful :+1:

No dice:
![image](https://user-images.githubusercontent.com/1909698/113664428-b792ea00-9679-11eb-9af0-1f4e486ef6ca.png)

With filter commented out (this works)
![image](https://user-images.githubusercontent.com/1909698/113664646-1a848100-967a-11eb-9de7-eaa69da35a0a.png)

Did a `git bisect 78bb434 origin/main` just to make sure the bad commit was the isDisabled introduction and it is: 

```
$ git bisect good
d7cdc2a7729ab02a2280b4be90ba618dc327db15 is the first bad commit
commit d7cdc2a7729ab02a2280b4be90ba618dc327db15
Author: Carlos Alessandro Ribeiro <cribeiro84@gmail.com>
Date:   Fri Apr 2 20:35:05 2021 -0300

    Bugfix/ignore disabled repos (#178)

    * Fixing isDisabled repos

    * trying to fix dependency tree

    * Fix for unselected proejcts on load PR manager without filter.

    * Trying to fix broken links

    Co-authored-by: Carlos Alessandro Ribeiro <carlos_alessandro@swissre.com>

 package-lock.json               | 32539 +++++++++++++++++++++++++++++++-------
 package.json                    |    12 +-
 src/models/PullRequestModel.tsx |     5 +
 src/tabs/PullRequestsTab.tsx    |   112 +-
 4 files changed, 26614 insertions(+), 6054 deletions(-)
```

Then I realized you just got your boolean logic bungled! On Server 2020, `r.isDisabled !== undefined` will always return false.

We want to keep all repos where the property is undefined _or_ not disabled. If the API ever starts returning it, then it'll be fine.

`const repos = (await this.gitClient.getRepositories(projectId, true) as GitRepositoryModel[]).filter(r => r.isDisabled === undefined || r.isDisabled === false);`

Voila
![image](https://user-images.githubusercontent.com/1909698/113668400-2d9a4f80-9680-11eb-9aed-4a8ebfc72f34.png)

See my PR!

**Comment by cribeiro84** [comment]
Thanks @InKahootz for the PR! It has been released and hopefully it's now fixed! Thank you so much for the contribution!

**Comment by Herve-M** [comment]
@cribeiro84 / @InKahootz  Still have the issue with the last update, 2.20210405.1 :/

**Comment by InKahootz** [comment]
That's an older version, or at least is should be. 2.20210405.1 is for commit `efa6a6a`.

The latest is 2.20210406.1. Might take a little bit to show up but the pipeline showing that it was built and pushed is here: 
https://dev.azure.com/caixaazul/Pull%20Request%20Manager%20Hub/_build/results?buildId=226&view=results

**Comment by agileramblings** [comment]
It is working now guys! Great work!! Thanks for a great extension @cribeiro84 

![image](https://user-images.githubusercontent.com/9729653/113875662-3cfac500-9774-11eb-96a2-fd578390d6ce.png)

**Comment by cribeiro84** [comment]
Amazing! Thank all of you for raising the issues and PR! Thanks @InKahootz for the contribution 

Don't forget to rate the extension in the marketplace that helps to get more contributions ;-)

**Comment by sunnynagavo** [comment]
i am facing same problem again,
