### ISSUE TITLE
Unable to view PRs with latest update(s)

### ISSUE THREAD

**Issue by purduekenny** [cribeiro84/azure-devops-pull-request-hub#185]
**Describe the bug**
None of the PRs load on my on-premise version of ADO.

**To Reproduce**
1. Visit landing page for the extension
2. Loading icon spins without ever progressing to show PRs

**Expected behavior**
Previously, the page loaded the PRs within a second with no issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/1843220/113772553-d5e8fc00-96f2-11eb-9923-e95bac8dfe0a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 87

**Additional context**
It was working at the end of last week without any issues and I noticed that there are a few updates this past weekend that were installed.

**Comment by cribeiro84** [comment]
thanks for raising this issue. 

Would you mind to share more details? Such as: console tab from developer tools (F12)? Not clear what’s going on with your instance.

**Comment by purduekenny** [comment]
Yes, I sure will! Let me know what else you'd like. 

![image](https://user-images.githubusercontent.com/1843220/113800917-ce8f1600-9725-11eb-83ed-a3184097bc19.png)

**Comment by cribeiro84** [comment]
Thanks for sharing it! It seems the API version has changed and your OnPrem server does not support it. Let me check if I can revert the change to a lower API version. 

In meantime, would you be able to upgrade the version of your ADO server? Is it feasible?

**Comment by purduekenny** [comment]
We're actually in the procurement stage to update ADO to the current version. Currently, the version is Version Dev17.M153.5.

**Comment by aldonetti** [comment]
> 
> 
> We're actually in the procurement stage to update ADO to the current version. Currently, the version is Version Dev17.M153.5. It will be several weeks until that's realized and your tool is immensely helpful to me. If the change is of minimal effort, I would be very appreciative; however, if it's a problem that's only affecting me I understand if you decide a `wontfix` solution, instead. stuck_out_tongue_winking_eye

I actually get the same issue - a few days ago it was workign correctly. now I don't see any PR listed (I see the project names, but not the repo names in the filters - looks like it's not getting the list of repos ...)

**Comment by bortolin** [comment]
I have same problem with on-prem Azure DevOps Server 2019 Update 1.1.

TFS.WebApi.Exception: The requested REST API version of 5.2 is out of range for this server. The latest REST API version this server supports is 5.1.

**Comment by millusdk** [comment]
We have exactly the same issue running Dev17.M153.3, and would also very much appreciate it if it is possible to revert to a lower API-version

**Comment by millusdk** [comment]
Hi Cribeiro,

Thank you very much for looking into this. I very much appreciate the work you put into this plugin, it helps us a lot, that being said, please don't feel obligated to push something out before the weekend, I can easily wait a little longer if you have more time to look into this in the coming weeks.

I have great respect for the work that you Open Source maintainers do, it is often an ungrateful job. I have just donated to the project as a thank you for the work that you do to provide this tool for us.

Best regards,
Emil

**Comment by cribeiro84** [comment]
Hi Emil,
I really appreciate the donation! I'm pleased to help as much as I can and I really like open source projects too, I love to share things with everyone that helps on a daily basis. 

;-)

**Comment by cribeiro84** [comment]
Hi @millusdk - I just released a new version of the extension. Could you please check if is it working fine now?
I've checked here and now it's using again API version 5.1 ;-)

Thank you so much

**Comment by millusdk** [comment]
Outer instance haven't registered that a new version is available yet, but as soon as it does I will test it

**Comment by purduekenny** [comment]
Yeah, same here.

**Comment by cribeiro84** [comment]
Hey guys, did it work? I'm curious ;-)

**Comment by bortolin** [comment]
Very good !!!! I have updated to the latest version and now it works perfectly.

thank you very much @cribeiro84

**Comment by cribeiro84** [comment]
Great!! Thanks a lot for the feedback!

I was wondering whether would make sense to have a separated extension only for ADO Server so it could avoid breaking changes for all of you. @millusdk @purduekenny @aldonetti @bortolin - would that facilitate for you?

Thanks for your feedback and inputs!

**Comment by purduekenny** [comment]
Thanks for the fix, I've confirmed it's working on my server as well. If you think that's the best course of action for your project, then do what's best for you. Pinging me when you release it will allow me to install that version of the extension. Do you plan on updating both with the same feature sets?

**Comment by cribeiro84** [comment]
@purduekenny - the idea is to keep them in sync with new features and fixes, however, due the limitations of API versioning in ADO Server, some features could be left aside in comparison with ADO Services. Nevertheless, my feeling is that most of the features will be available because ADO team is not evolving so much the APIs in ADO.

**Comment by millusdk** [comment]
@cribeiro84 It works for us as well. Thank you very much for the very quick turn around for a fix.. That is greatly appreciated.

Personally I would like a version of the package that supports Azure DevOps Server 2019 for as long as we are on it. But it has to make sense for you to maintain to version of the package, one for Azure DevOps Server 2019+ and one for Azure DevOps Services.

**Comment by aldonetti** [comment]
> Hey guys, did it work? I'm curious ;-)

Yes, thank you @cribeiro84 ! Works well now.
I wonder if it would be better to just (or also)  make the extension installable manually, rather than from the marketplace? just to make sure it can stay/work as-is, for as long as there's no breaking change induced by the platform ...
