### ISSUE TITLE
Pull Request Manager Hub is taking longer than expected to load.

### ISSUE THREAD

**Issue by TobiStr** [cribeiro84/azure-devops-pull-request-hub#193]
**Describe the bug**
When trying to use the Pull Request Manager, it only displays a loading animantion and the message "Pull Request Manager Hub is taking longer than expected to load." above. (Waited for >10 minutes)

**To Reproduce**
1. Install Pull Request Manager
2. Navigate to Devops (https://dev.azure.com/...) -> Repos -> Pull Request Manager Hub

**Expected behavior**
Manager shows up normally.

**Desktop:**
 - Browser: Google Chrome Version 90.0.4430.72 (64bit)

**Additional context**
In case it might be another Extension that is interferring, i have installed the following:
![image](https://user-images.githubusercontent.com/54748454/115377913-5833ee80-a1d0-11eb-8203-9e4538a0f9e7.png)

**Comment by cribeiro84** [comment]
Hi @TobiStr 
That could be something related to ADO because we don't host anything outside of ADO boundaries and all APIs are standards and used from ADO too. How many projects and repos do you have? That could make the things to slow down.

**Comment by TobiStr** [comment]
Hi @cribeiro84 
Thank you for the quick reply. Sorry, but what is ADO?
We currently have 14 projects.

**Comment by cribeiro84** [comment]
Hello @TobiStr 
ADO is Azure DevOps, sorry for the confusion. 14 projects is not that much so it shouldn't take too long. Can you check if in the console (developer tools of the browser) if any error is shown there? If so, could you please share it with me?

**Comment by TobiStr** [comment]
For some reason, it works now without me doing anything about it... Thank you anyway :)
