### ISSUE TITLE
Sorting Changes Lost On Refresh

### ISSUE THREAD

**Issue by croixnewson** [cribeiro84/azure-devops-pull-request-hub#203]
**Describe the bug**
Sorting change lost on refresh, despite icon indicating sort still active.

**To Reproduce**
1. go to pull request manager hub in azure devops
2. sort by a column
3. refresh the page
4. note that the arrow still shows in the direction indicating the sort you'd picked, but the data is no longer sorted in that way.

**Expected behavior**
The sort should hold.

**Screenshots**
Before refresh:
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/44614441/127042077-69526030-1a9d-46b3-985d-4ddb8517a381.png">

After refresh: 
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/44614441/127042145-38354b02-86b6-44bf-bbdc-5621ea29dad8.png">

**Desktop (please complete the following information):**
Mac OS Big Sur, Safari

**Comment by Xerillio** [comment]
@cribeiro84 I opened a PR that fixes this by remembering which direction you've chosen to sort in. Let me know if that's acceptable.
