### ISSUE TITLE
You need the Git 'GenericRead' permission to perform this action

### ISSUE THREAD

**Issue by darrenhull** [cribeiro84/azure-devops-pull-request-hub#205]
**Describe the bug**
When loading the plugin the following message is shown:

There was an error during the extension load: TFS.WebApi.Exception: TF401027: You need the Git 'GenericRead' permission to perform this action. Details: identity '{user identity}', scope 'repository'.

The user has full permissions on the root repository. However, the root repository does contain a space: "My Repository" I was wondering if this is causing the issue.

**Comment by darrenhull** [comment]
I have just found a repository that did not have the read permission set, I changed that and it has fixed my issue.

**Comment by johngladp** [comment]
Just tried out this extension and this error message was displayed and no details of any of the PRs was displayed.  This is with TFS on premises v2019 (Version Dev17.M153.5).  The extension version says: 2.20210622.2 (Latest).

**Comment by cribeiro84** [comment]
> Just tried out this extension and this error message was displayed and no details of any of the PRs was displayed. This is with TFS on premises v2019 (Version Dev17.M153.5). The extension version says: 2.20210622.2 (Latest).

Hello @johngladp - in the past a few people were getting this error due the disabled repos also. Would you be able to check that?

**Comment by johngladp** [comment]
> > Just tried out this extension and this error message was displayed and no details of any of the PRs was displayed. This is with TFS on premises v2019 (Version Dev17.M153.5). The extension version says: 2.20210622.2 (Latest).
> 
> Hello @johngladp - in the past a few people were getting this error due the disabled repos also. Would you be able to check that?

Hi, just having a look through the repos now (there are many).  There doesn't appear to be a disable option on any of the repos in this project (is that something added after the 2019 version we're running?)  I did spot one repo that has "not set" permissions for my identity.

**Comment by cribeiro84** [comment]
Got it, to be honest I'm not sure if this option is new or not. The option is shown up in the Project Settings > Repos > Repo details as follows

![image](https://user-images.githubusercontent.com/328635/139716098-e1942d7c-a4cc-4133-b6c3-388a20b9e313.jpeg)

Also in the repo you were Not Set with the permission - do you have any group that has permissions and your identity is member of?

Many thanks

**Comment by johngladp** [comment]
This is the view on our server:
![image](https://user-images.githubusercontent.com/25591355/139716562-c955b2aa-b45b-4ec1-9335-ef783521dd43.png)

Regarding the 1 repo that has different permissions (all the others inherit permissions from the project).  I do not have read (or any other) permissions on that particular repo.  Whilst I'm a project admin, that particular project has it's own admin group and developer groups, I am a member of neither.  I just tried another limited user account (on another machine) that has read permissions to that particular repo and the dashboard did show up a handful of the repos (3 of about 40 or so) and not display that error message.

**Comment by johngladp** [comment]
To follow up on this again.  I just tried granting myself read permission on the single repo that is tightly locked down and the dashboard extension started working correctly.  If I unset the read permission on that repo, it no longer works from my user identity.

**Comment by cribeiro84** [comment]
The problem is, from the extension perspective, we fetch all PRs from all available repos in the organization. Therefore, it requires at least the Read permission to read the minimal data. There is no option in the APIs to fetch only ones the user has access to, sorry about that.
