### ISSUE TITLE
Repositories dropdown only shows the repositories for last-selected project

### ISSUE THREAD

**Issue by alexpilon666** [cribeiro84/azure-devops-pull-request-hub#214]
**Describe the bug**
When multiple projects are selected, the `Repositories` dropdown only shows the repositories of the last-selected project.

**To Reproduce**
1. Install the extension
2. Go into a project > Repos > PRMH
3. Select multiple projects
4. Click on `Repositories` dropdown and search (manually or with the search box) for a repository contained in the original project: It's not there

**Expected behavior**
The `Repositories` dropdown should contain all the repositories, for all the projects that are currently selected.

**Screenshots**
Single project, single repository: ![2022-02-11 13_13_41](https://user-images.githubusercontent.com/35434424/153646797-4d993f39-0e8f-4fe3-994e-cd38602ea632.png)

Adding second project, the initial repository is not present: ![2022-02-11 13_14_20](https://user-images.githubusercontent.com/35434424/153646804-1e253cec-4154-40b8-9b0e-c019731e41d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Chrome
 - Version: v98.0.4758.82 64-bit (latest version)

**Additional context**

**Comment by cribeiro84** [comment]
Fixed in the latest PR #218
