### ISSUE TITLE
Dashboard does not load on on-premise Microsoft Visual Studio Team Foundation Server Version 16.131.28507.4

### ISSUE THREAD

**Issue by kazepreaux** [cribeiro84/azure-devops-pull-request-hub#23]
Hi,
The dashboard does not load on the on-premise version of Microsoft Visual Studio Team Foundation Server 2018 (16.131.28507.4).

Error is: "Pull Request Manager Hub by Carlos Alessandro Ribeiro failed to load.Learn More about this extension, including available support options."

Please let me know if this version is not supported.

**Comment by cribeiro84** [comment]
Hello @kazepreaux,
Thanks for the information. I did not test the extension on TFS Server because I don't have access to it. Would you mind to provide more details for me to have a better understanding about what's happening and perhaps try to fix it?

1. Log details of the error
2. If possible, a print screen of the Network and Console tabs using the Developers Tool (Chrome or Firefox) 

Thank you

**Comment by kazepreaux** [comment]
Here is the log from the console tab in developers tool:
[1568382149229.log](https://github.com/cribeiro84/azure-devops-pull-request-hub/files/3610291/1568382149229.log)

I also taken a screenshot of it:
![image](https://user-images.githubusercontent.com/26405651/64867364-29898580-d635-11e9-85a9-fcc6f41d102f.png)

Sadly, I would not know where to get any TFS Server logs.

**Comment by cribeiro84** [comment]
Just to understand, you are using the Team Foundation Server and not the Azure DevOps Server, right? If so, I believe this is the issue, the extension is meant only for Azure DevOps Services and Server because I'm using the latest version of its SDK.

**Comment by kazepreaux** [comment]
Yes I am, your extension is listed to be supported for the following:
![image](https://user-images.githubusercontent.com/26405651/64942119-26261200-d860-11e9-90b8-bed19a4fd864.png)

If there is no way to fix it, I'll uninstall it :). 
But I recommend removing unsupported versions.

**Comment by cribeiro84** [comment]
Hello @kazepreaux,
Sorry for this but unfortunately, at this moment I won't be able to fix it once it would require downgrade of the SDK. I hope in the future I can fix it.

**Comment by cribeiro84** [comment]
@kazepreaux the new version is already released. Feel free to test it.
Thanks a lot for your feedback and sorry for the delay.
