### ISSUE TITLE
Question: what does the "Team" filter filters?

### ISSUE THREAD

**Issue by bergamin** [cribeiro84/azure-devops-pull-request-hub#248]
We manage several teams who work on over a hundred repositories. As a reviewer, I need to review code from certain teams but not others and some repositories are maintained by more than one team.

I want to make filtering easier for all reviewers, and right now filtering by team doesn't bring any results, probably because we are not setting something. I want to know what this something is.

What does Pull Request Manager Hub use as a parameter for team filtering? Is that a setting on the repo, a setting on the developer's profile, a setting on the PR itself, or something else?

If you could also describe how to edit such info, it would be wonderful as well

Thanks

**Comment by Xerillio** [comment]
In an Azure DevOps project you can [set up one or more teams][1]. If the PR creator belongs to **one or more** of the teams chosen in your filter their PR will show up. All existing teams **in the selected** projects should show up as choices in the filter dropdown.

[1]: https://learn.microsoft.com/en-us/azure/devops/organizations/settings/add-teams?view=azure-devops&tabs=preview-page

**Comment by bergamin** [comment]
That makes sense. Our teams were probably created empty then. I'll bring this issue forward so we can make things easier for everybody

Thanks a million!

**Comment by cribeiro84** [comment]
Sorry for the delay guys in replying in back, thanks @Xerillio for explaining it! The main goal of the Reviewers filter is to group all the names and teams found within the PRs, so, if you create a PR policy where it automatically adds the teams you need as required reviewers (or even optionals), it will be listed there and you can filter it out.

**Comment by bergamin** [comment]
Oi, Carlos. Tranquilo?

We have that as well, but the team used for required reviewers is the tech leaders team, so it won't help for this. All PRs have the same team as required reviewer.

When I'm back from the end of year recess, I'll see with PMs to populate the devs' teams

**Comment by cribeiro84** [comment]
Thanks for the clarification @bergamin - is this case, what I would recommend is to add tags for the PRs and filter it out by this information. 
Muito obrigado 😄
