### ISSUE TITLE
Syntax highlighting for .razor files.

### ISSUE THREAD

**Issue by KevinH404** [cribeiro84/azure-devops-pull-request-hub#257]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, its just that when doing PRs its much nicer to have proper syntax highlighting while reviewing .razor files. Other files seem to have correct highlighting.

**Describe alternatives you've considered**
I currently checkout the branch locally and open the files on VS2022.

**Additional context**

![image](https://user-images.githubusercontent.com/12038888/214736138-e645e260-a6ed-41eb-835b-f0a6863ecd4d.png)

![image](https://user-images.githubusercontent.com/12038888/214736183-4428f7aa-3f73-4c20-9ea2-a45c08d878b2.png)

**Comment by cribeiro84** [comment]
Dear @KevinH404 - this feature must be requested to Azure DevOps Team once the PR page is a built-in feature of ADO and not related to this extension. I am closing this issue.

**Comment by KevinH404** [comment]
@cribeiro84 thank you for the quick response. Do you know where can I read more about that? do they have a news page or something? Sorry about the trouble.

**Comment by cribeiro84** [comment]
No worries @KevinH404 - my pleasure to help. I believe that you can submit feature request on the top right corner of ADO, there is a button for Support/Feedback.
