### ISSUE TITLE
Ability to Filter our Draft PRs on Azure DevOps

### ISSUE THREAD

**Issue by hanneswidrig** [cribeiro84/azure-devops-pull-request-hub#28]
It would be excellent if we had the ability to filter out draft PRs, there's currently no way to filter them out in either your extension or Azure Dev Ops. 
![image](https://user-images.githubusercontent.com/3399497/65893265-aa56ba00-e375-11e9-9834-171aeeb67527.png)

**Comment by cribeiro84** [comment]
Hello @hanneswidrig,
thanks for the suggestion. It will be considered to be implemented in the next releases.

**Comment by hanneswidrig** [comment]
Hey @cribeiro84, I think I will attempt to implement this feature and then make a pull request for you to look at.

**Comment by cribeiro84** [comment]
Hello @hanneswidrig,
I'm working on a few improvements (UI and code clean-up) and bugfixes and if you don't mind, I can add also the new filter as you requested. With that, in the next release it will already have it for you :-)

This is how it will look like:
![image](https://user-images.githubusercontent.com/328635/66051962-2e3fac00-e506-11e9-8578-f279f8e3a455.png)

**Comment by cribeiro84** [comment]
Closing this issue once the last release implements the new filter as requested

**Comment by hanneswidrig** [comment]
Well awesome, thanks for adding the feature.

**Comment by cribeiro84** [comment]
My pleasure! Please also give your feedback on the rating process of Azure DevOps marketplace, it will be great. :-)
