### ISSUE TITLE
License for your project

### ISSUE THREAD

**Issue by hanneswidrig** [cribeiro84/azure-devops-pull-request-hub#34]
>When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

It would be advisable if you added a license for your project. Right now all rights are reserved for you.
https://choosealicense.com/

**Comment by cribeiro84** [comment]
Hey @hanneswidrig,
Thanks for the heads up! I’ve missed that but now it’s fixed. I just merged the license details under MIT. I believe this is the most open one.
