### ISSUE TITLE
Show current user PRs by default

### ISSUE THREAD

**Issue by edgariscoding** [cribeiro84/azure-devops-pull-request-hub#54]
Could this extension be configured to show only the current user's PRs when first loading?

**Comment by cribeiro84** [comment]
@edgariscoding - Thanks for this feedback. It will be considered as a new feature for future releases.
It's planned already to have the current state saved to facilitate next time you visit the extension to capture where exactly you left.

**Comment by cribeiro84** [comment]
I'm closing this issue once it's already considered in the future releases.

**Comment by edgariscoding** [comment]
@cribeiro84 Thank you! Having it remember the filter would be all we need. Looking forward to this enhancement!

**Comment by cribeiro84** [comment]
Yeah, that’s the ideia but saving the current state alongside with the new filter will solve both problems 😃
