### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'text' of undefined at n.renderSelectedItems (DropdownFilterBarItem.js:98)

### ISSUE THREAD

**Issue by webbermt** [cribeiro84/azure-devops-pull-request-hub#55]
The page is failing to load with error: Uncaught (in promise) TypeError: Cannot read property 'text' of undefined at n.renderSelectedItems (DropdownFilterBarItem.js:98).  The following line is failing when selection.value[0].beginIndex = -1.  This is typically the case when there is no selection in the dropdown.

var selectedText = items[selection.value[0].beginIndex].text || "";

**Comment by cribeiro84** [comment]
@webbermt thanks for reporting this. I will work on this issue in the future releases.

**Comment by cribeiro84** [comment]
@webbermt - would you mind to provide a few more details to help me to troubleshoot/simulate this issue?

- Are you using Azure DevOps Services (Cloud) or Server?
- Is there any other additional console error?

Thank you

**Comment by webbermt** [comment]
I'm using Azure DevOps Services (Cloud).
The only console error I see in Chrome is the following:
DropdownFilterBarItem.js:98 Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:98)
    at U (DropdownExpandableButton.js:18)
    at Xo (react-dom.production.min.js:3274)
    at Mi (react-dom.production.min.js:3899)
    at Ga (react-dom.production.min.js:5514)
    at $a (react-dom.production.min.js:5536)
    at js (react-dom.production.min.js:5958)
    at Os (react-dom.production.min.js:5925)
    at Ts (react-dom.production.min.js:5860)
    at es (react-dom.production.min.js:5787)
n.renderSelectedItems @ DropdownFilterBarItem.js:98
U @ DropdownExpandableButton.js:18
Xo @ react-dom.production.min.js:3274
Mi @ react-dom.production.min.js:3899
Ga @ react-dom.production.min.js:5514
$a @ react-dom.production.min.js:5536
js @ react-dom.production.min.js:5958
Os @ react-dom.production.min.js:5925
Ts @ react-dom.production.min.js:5860
es @ react-dom.production.min.js:5787
enqueueSetState @ react-dom.production.min.js:2790
x.setState @ react.production.min.js:72
value @ PullRequestsTab.tsx:321
(anonymous) @ PullRequestsTab.tsx:300
Promise.finally (async)
(anonymous) @ PullRequestsTab.tsx:293
u @ runtime.js:45
(anonymous) @ runtime.js:264
E.forEach.e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ PullRequestsTab.tsx:68
(anonymous) @ PullRequestsTab.tsx:176
u @ runtime.js:45
(anonymous) @ runtime.js:264
E.forEach.e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ PullRequestsTab.tsx:68
(anonymous) @ PullRequestsTab.tsx:135
u @ runtime.js:45
(anonymous) @ runtime.js:264
E.forEach.e.<computed> @ runtime.js:98
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ PullRequestsTab.tsx:68
co @ react-dom.production.min.js:2854
ki @ react-dom.production.min.js:3759
Mi @ react-dom.production.min.js:3960
Ga @ react-dom.production.min.js:5514
$a @ react-dom.production.min.js:5536
js @ react-dom.production.min.js:5958
Os @ react-dom.production.min.js:5925
Ts @ react-dom.production.min.js:5860
es @ react-dom.production.min.js:5787
zs @ react-dom.production.min.js:6077
qs @ react-dom.production.min.js:6085
Ws.render @ react-dom.production.min.js:6276
(anonymous) @ react-dom.production.min.js:6360
Ls @ react-dom.production.min.js:6007
Ks @ react-dom.production.min.js:6359
render @ react-dom.production.min.js:6390
586 @ common.tsx:8
l @ index.html:1
257 @ main.5607f647.chunk.js:1
l @ index.html:1
f @ index.html:1
e @ index.html:1
(anonymous) @ main.5607f647.chunk.js:1

**Comment by cribeiro84** [comment]
@webbermt - I'm not able to reproduce the issue you are facing. I've tried several things.
Would you be able to provide more details on it?

 - Are you using the latest version?
 - Does your project has repositories?
 - Can you ensure that you are using the latest version of the extension?
 - Is this happening on the first load of the extension or does it happen after a filter is applied?

Thanks in advance.

**Comment by webbermt** [comment]
We are using the 1.20191214.1 (Latest) version.  We have over 100 team projects with some projects containing over 100 repositories.  The error happens on first load of the extension.  However, the extension was working fine for several weeks and then just stopped working for me.  We have other users that are able to use the extension.  I don't believe there are any filters applied.  If I manually change the selection.value[0].beginIndex from -1 to 0, then the page rendered correctly but has the first team project selected in the filter drop down.  I also noticed that the project with the most repositories is not listed in the dropdown.  I wonder if the large number of repositories is causing the problem.

**Comment by cribeiro84** [comment]
Thanks a lot for all the details. I believe I've found the issue and I'm working on it to release a new version in the next days with the bug fixes. Sorry for the inconvenience.

**Comment by cribeiro84** [comment]
@webbermt - I just released a new version of the extension. I couldn't simulate the issue but I did some refactoring of the code to handle in a better way the async calls and exception handling.

Would you mind to test it again?

Thanks a lot

**Comment by btastic** [comment]
I have this issue as well. I went to the "Project" drop down and clicked on "Clear (X)". After that, the dashboard does not load with the error described in this issue. 

Maybe it helps to reproduce it, as I can no longer use it.
