### ISSUE TITLE
It would be useful to have the ability to query for PRs across an entire organization

### ISSUE THREAD

**Issue by ApolonTorq** [cribeiro84/azure-devops-pull-request-hub#63]
It appears that the extension works solely within the context of a devops project. Something like the query checkbox which allows the query to run across all projects would be useful for summarizing PRs across an organization.

**Comment by cribeiro84** [comment]
Hello @ApolonTorq, the extension providers a filter option to fetch all PRs of a single project at a time. It was intentional to have this behavior due the fact it could impact the performance of the extension load time to fetch all PRs across all projects of an organization.

Thank you.

**Comment by stealthcold** [comment]
I was expecting a feature like that too 😔

**Comment by spaasis** [comment]
Any chance for considering this for a future release? It's currently quite painful to see all the pull requests that have been assigned to any team I'm a part of, since the only way to do this seems to be to manually go through each project (which there are plenty...)
