### ISSUE TITLE
Ability to save/share filter

### ISSUE THREAD

**Issue by johnny2hunter** [cribeiro84/azure-devops-pull-request-hub#73]
As an AzureDevOps user I want to be able to save my filter and share it (via URL with parameters?) so me or my colleague can see results with the same filter during opening of PR hub without re-applying it from scratch

**Comment by cribeiro84** [comment]
Thanks for the suggestion, I’m working already on implementing this feature and I hope to deliver it as soon as possible.

**Comment by ericgoudriaan** [comment]
Hi, we are using this extension (works great) and hope that this feature will be available soon. Do you have some kind of indication as to when this feature is released? Thx

**Comment by alexander-d** [comment]
@cribeiro84 saving doesn't help for sharing. It would be great if we could share the save configurations, and as suggested in the OP via URL with parameters seems like a natural choice.

**Comment by kimsey0** [comment]
Perhaps it could just be something simple, like saving the same JSON that's currently put in local storage to the location hash? I've made a draft of that in #174.
