### ISSUE TITLE
redirecting to 'https://caribeiro84.gallerycdn.vsassets.io/'

### ISSUE THREAD

**Issue by vinodkurienalex** [cribeiro84/azure-devops-pull-request-hub#74]
Installed the extension today, love the view and the filtering options and the speed of loading is pretty good too. But every PR is redirecting to https://caribeiro84.gallerycdn.vsassets.io/ as base URL
and 'Resource not found' error displays ?

**Comment by cribeiro84** [comment]
Thanks for your inputs and feedback! That issue was not supposed to happen. Would you mind to share some details? Are you using Azure DevOps Cloud or OnPrem? If OnPrem, which version?

Thank you very much

**Comment by vinodkurienalex** [comment]
thanks for reply .. i am using Azure Devops ..
![image](https://user-images.githubusercontent.com/3693455/73504520-ad31ec00-43f5-11ea-9107-cc0a3a3c231d.png)

**Comment by cribeiro84** [comment]
@vinodkurienalex thanks for sending the details. I was not able to simulate this issue. 
Are you using from which browser? Is there any error in the console tab of developer tools of your browser? 


Thanks a lot

**Comment by vinodkurienalex** [comment]
thanks . I can now confirm this is a browser specific issue.
I am using Brave browser Version 0.70.121 Chromium: 78.0.3904.70

The issue is not coming when i try in Google Chrome or Edge.
Would you be fixing this for Brave

**Comment by cribeiro84** [comment]
@vinodkurienalex I'm not aware of this browser and I may not be able to make tests on it soon. I would recommend you for now to use Chrome, Firefox or Edge. 

Thank you very much
