### ISSUE TITLE
Duplicating the last item in the list

### ISSUE THREAD

**Issue by smhbhdr** [cribeiro84/azure-devops-pull-request-hub#76]
Dashboard duplicates the last Pull Request in the list and shows it in all projects in the team despite it belongs to only one project.

1 - Select a project (Project A) that does not have any PR (Pull Request). See nothing is listed.
2 - Change the project from filter bar to a project (Project B) that has more than one active PR.
3 - Change the project back to the Project A and see that last item from previous one is listed.
4 - Change the project to the Project B and see the last item is duplicated.
5 - Click Refresh button and see it's still duplicated.
6 - Click [Ctrl + F5] to get duplicated item removed.

Tested on Microsoft Edge (Version 79.0.309.71)

**Comment by cribeiro84** [comment]
Thanks @smhbhdr for raising this issue. We are aware of this bug already and it will be fixed in the next release alongside with many good new features :-)

Thank you.
