### ISSUE TITLE
Add new Alternate Status items

### ISSUE THREAD

**Issue by cribeiro84** [cribeiro84/azure-devops-pull-request-hub#78]
- Completion Readiness based on the alternate Statuses (Comments resolved, PR policies, reviewers)
- Comments Resolved
- PR Policies passed

**Comment by adrianrbezzina** [comment]
Would be great if we also had filters here for Read for Completion or Waiting Review to be exact, these statuses:

![image](https://user-images.githubusercontent.com/7981600/77706634-0cd3fe80-7017-11ea-8e5e-af279f391962.png)

**Comment by bnm27** [comment]
In light of DevOps recent changes to make the 'Waiting on Author' status basically unusable for required reviewers (it no longer gets reset automatically), I would also really like to see a status badge or separate icon for unresolved comments
