### ISSUE TITLE
Only the first 100 team projects are displayed

### ISSUE THREAD

**Issue by webbermt** [cribeiro84/azure-devops-pull-request-hub#81]
When more than 100 team projects exist in an organization, the projects api will only return the first 100 team projects and then return the x-ms-continuationtoken response header to be used on subsequent calls to get the next batch of team projects.  It doesn't appear that the extension is properly handling this situation to get all the team projects.

**Comment by cribeiro84** [comment]
Hello @webbermt 
thanks for the feedback. We will work on it to release in the future releases.

**Comment by cribeiro84** [comment]
@webbermt - we did not find anywhere in the SDK how to get all Projects at once, the SDK does not provide any additional parameter to properly filter/page the results or, as you mentioned, the x-ms-continuationToken in the header. It was supposed to bring all projects.

**Comment by webbermt** [comment]
I believe the following function needs to be updated to use the getProjects call with the continuationToken parameter:

  private async getTeamProjects(): Promise<TeamProjectReference[]> {
    const projects = (await this.coreClient.getProjects()).sort(
      Data.sortMethod
    );
    return projects;
  }

getProjects API reference:
https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/corerestclient?view=azdevops-ext-latest#getprojects-any--number--number--string--boolean-


Even though the documentation clearly states that all projects will be returned, it doesn't return more than 100 on a single call.  If this works like the Projects List API, then it will only return the first 100 projects and return the x-ms-continuationtoken response header so it can be called again by passing in the value from the x-ms-continuationtoken response header to get up to the next 100 projects.
https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-5.1

You could also create 101 team projects in your Azure DevOps test instance to see the behavior.  If you go to the Pull Request Manager Hub page you should see that one of the projects is missing from the projects filter dropdown.

**Comment by webbermt** [comment]
Thank you!  I can confirm that the changes in #141 have fixed the issue.

**Comment by cribeiro84** [comment]
@webbermt thanks for the feedback!! I'm glad that's now finally fixed. Don't forget to rate our extension on the marketplace to help us on being the best PR Manager for ADO :-)
