### ISSUE TITLE
Active Pull Request Row Icon to Policy Status

### ISSUE THREAD

**Issue by mack0196** [cribeiro84/azure-devops-pull-request-hub#83]
My team likes to scan the active pull request view for PR that need attention. Instead of the icon showing an individuals status on the PR, can it be set to the PR policy status?

![image](https://user-images.githubusercontent.com/6463105/75375705-3c66de00-5894-11ea-8ae1-417a43008ac5.png)

**Comment by cribeiro84** [comment]
Hi @mack0196 - we are working on it to sync the PR Status to be linked to the whole Policy Statuses. We did not make it yet because we are ensuring the APIs we are calling and validations are consistent. 

Thanks a lot

**Comment by natebunton** [comment]
I've got a branch policy with "Status Check" policy on it and the "policies icon" is not accurate.

![image](https://user-images.githubusercontent.com/7373116/86394076-9113ce80-bc63-11ea-9fa5-f365bd2c9f58.png)

![image](https://user-images.githubusercontent.com/7373116/86394124-ab4dac80-bc63-11ea-8929-2f319be7105e.png)

**Comment by cribeiro84** [comment]
The status now should be in sync with the policies. Would you mind to check from your side?
Thanks

**Comment by natebunton** [comment]
I checked and it is still not working
![image](https://user-images.githubusercontent.com/7373116/86607087-75b00880-bf6e-11ea-85aa-090f6f4323d1.png)

![image](https://user-images.githubusercontent.com/7373116/86607141-82ccf780-bf6e-11ea-865b-f454166e5fb7.png)

Extension details
A complete and friendly Pull Request Hub to manage all your repositories' PRs with must have filters at one simplified view.
Publisher
Carlos Alessandro Ribeiro
Installed version
1.20200705.2 (Latest)
Last updated
Jul 5, 2020 at 8:11 PM CDT
