### ISSUE TITLE
Can't install extension on devops server 2019

### ISSUE THREAD

**Issue by ribeirothalles** [cribeiro84/azure-devops-pull-request-hub#84]
Hey Carlos!
I'm really interested in testing your extension in my daily code reviews. But unfortunately, i couldn't install it to my company's Azure DevOps Server 2019. It says this extension isn't compatible with the Azure DevOps API Version. Detailed error below:

Unable to publish extension due to:
- Incompatible API version (5.1)

Can you help me?
Thanks!!

**Comment by cribeiro84** [comment]
Hey @ribeirothalles - it seems we are family :-p
Just kidding - we had to upgrade to 5.1 version to be able to evolve the extension. Sorry about that! However, I have an option for you, if I may. You can fork our repo, change the settings to be compatible with your version, run the command to create the extension (DEV mode or release) and try to import to your Azure DevOps server. Would that work for you?

We will be available in case you need any help.

Thanks a lot

**Comment by ribeirothalles** [comment]
hahaha, we probably are!
Thanks for the suggestion, we are going to try it.

Best regards!

**Comment by cribeiro84** [comment]
@ribeirothalles feel free to ping me in case you need any support... :-)
