### ISSUE TITLE
Filter to exclude Draft

### ISSUE THREAD

**Issue by jamesbaca** [cribeiro84/azure-devops-pull-request-hub#85]
It would be great to be able filter out any draft pull requests so that only non-drafts pulls that have actually been published can be shown in the hub. The current "IsDraft" #65 checkbox under "Alternative Status" changes the view to only show Drafts, which is the the opposite of what I would typically want!

To follow the checkbox pattern used so far I would suggest the following changes:

1. Create a new "Status" filter
2. Status filter has checkboxes for Draft, Published only (Omit Completed, Abandoned if this is too many queries as mentioned on previous issue #64)
3. Selecting either checkboxes filters the view to any pull requests matching either checked status.

**Comment by cribeiro84** [comment]
Hi @jamesbaca 
It's a great suggestion. thanks for this. We will include this idea in the future releases.

**Comment by snckirkmarken** [comment]
Or even modify the "Alternate Status" filter (which is no use for us at the moment) to make it just "Status", and then be able to select specific statuses, with the default to them *all* enabled?
