### ISSUE TITLE
Add Tags to Pull Request and Search Filter

### ISSUE THREAD

**Issue by rieslma** [cribeiro84/azure-devops-pull-request-hub#86]
Hi,
thank your for your nice PR Hub. 

Is it possible to add the Tags from a Pull Request to the Hub. We are tagging the PRs and often I want to filter only be a specific Tag.

greetings

**Comment by cribeiro84** [comment]
@rieslma thanks for this suggestion, we will evaluate the feature to be developed in the future releases.

**Comment by er1c** [comment]
+1 can the existing "labels" for a PR get added?

**Comment by rieslma** [comment]
@er1c yes in PR it calls Label, right

**Comment by snckirkmarken** [comment]
This would be incredibly useful for us, too.

**Comment by MichaelGithub13** [comment]
Hi!
Another great feature would be to add a priority. Either by ordering the PRs or setting a priority number. That would be a huge help in our daily work!
Thank you in advance!
BR
Michael
