### ISSUE TITLE
Add setting to open PR in same tab

### ISSUE THREAD

**Issue by bnm27** [cribeiro84/azure-devops-pull-request-hub#89]
Love the extension, been using it for a couple weeks and it is invaluable to me to not have to hop around to several repos making sure I don't have any pull requests pending. 

I would however like to request a setting to allow us to have the hub open pull requests in the same tab. The default Pull Request screen behaves this way and I would like it to be consistent, but mainly if you have DevOps "installed" as a desktop app (Chrome/Edge) then pull requests open outside of the app in another browser window.

DevOps acts as a single page application and doesn't launch new tabs all over the place.

**Comment by cribeiro84** [comment]
@bnm27 thanks a lot for your feedback... we really appreciate it!
We are working on new features and one of them is to have Preferences so anyone can configure some default behaviours. It will be available in the future releases.

:-)

**Comment by cribeiro84** [comment]
This issue will be taken on #132 - closing to avoid duplicated issues.

**Comment by bsivanov** [comment]
I frequently use middle-click (or CTRL+ mouse click, or _Open link in new tab_ command in the context menu) to open links in a new tab. Neither of these work with the PR links, nevertheless of the value of `Open PR in a new Window` setting in the UI. 

The convenience of making this command working would be that this would allow PRs to be open in a new tab in the background - this would allow me e.g. to click and open 5 PRs without losing the focus of the main view.
