### ISSUE TITLE
Loading Error after 3/23 update

### ISSUE THREAD

**Issue by ProbablyTacos** [cribeiro84/azure-devops-pull-request-hub#91]
Attempting to load the pull request hub results in the following error after the 3/23 update:
 There was an error during the extension load: SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

No security settings have been changed for the organization or projects

**Comment by cribeiro84** [comment]
thanks @ProbablyTacos for raising this issue and I'm for breaking the extension to run properly on your browser. It seems to be a settings in Chrome (if this is the browser you are using) that might cause this exception:

https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document
![image](https://user-images.githubusercontent.com/328635/77835717-2caa1600-712e-11ea-821b-ade745eda2af.png)

Could you please check if this is the case for you?

Thanks a lot

**Comment by ProbablyTacos** [comment]
That fixed it. thanks for the help

**Comment by cribeiro84** [comment]
thank you @ProbablyTacos for the feedback :-)
Feel free to raise issues or new suggestions for the extension. Also, I encourage you to become a contributor as well

Kind Regards
   Carlos
