### ISSUE TITLE
Remember filtered repositories

### ISSUE THREAD

**Issue by dloukola** [cribeiro84/azure-devops-pull-request-hub#92]
Steps

1. Open the repositories dropdown
2. select a few repositories
3. refresh the browser

Expected
- repositories to be remembered

Actual
- repositories reverted back to all

**Comment by cribeiro84** [comment]
@dloukola would you mind to share with me what`s your browser and its version?
I was not able to simulate the issue using my Chrome, Safari and Firefox on macOS. On all mentioned browsers, the selected repos were remembered correctly.

Thanks a lot

**Comment by dloukola** [comment]
Hi, sorry, I didn't seem to get a notification about this.

Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Pull Request Manager Hub: 1.20200213.1 (Latest)
Azure devops on-prem.

It is expected that remembering the filtered repositories even if you browser is closed and re-opened is retained? If that's the case, that is not happening for me.

**Comment by dloukola** [comment]
It looks like this is related to the use of localstorage as data storage instead of the azure devops data storage.
https://docs.microsoft.com/en-us/azure/devops/extend/develop/data-storage?view=azure-devops
