### ISSUE TITLE
Group Approvals Not Showing Correctly

### ISSUE THREAD

**Issue by kyleherzog** [cribeiro84/azure-devops-pull-request-hub#93]
We have group approval rules setup, where one approval from a group member is required, but the requestor cannot approve their own.  The PR hub does not appear to take into account that a  requestor cannot approve their own request.  It shows approved just as long as one person in the group has approved no matter what.

**Comment by cribeiro84** [comment]
@kyleherzog thanks for your feedback and we are aware of this issue. We are working on synchronise the statuses accordingly with the latest releases when we introduce the policies check and so on.... We will release the sync in the near future releases

thanks a lot
