### ISSUE TITLE
security?

### ISSUE THREAD

**Issue by jancg** [cribeiro84/azure-devops-pull-request-hub#94]
mr. Carlos Alessandro Ribeiro,

I have a question of conscience for you:

We are a team of 10-20 developers having a few dozen repositories in Azure. A collegue tipped your Pull Request Manager Hub. If we are to use your plug-in (is it correct to name it 'plug-in'?), what are the risks for us? Would you --in theory-- be able to retreive our source code? Could you --in theory-- do any harm? Your PR Manager Hub might be the first plug-in we are going to use. So we have no idea. Some guidance and reassurance is appreciated.

Kind Regards,
Jan C. de Graaf of BCC

**Comment by cribeiro84** [comment]
Hello @jancg thanks for your contact. With regards your question, we don't integrate our extension with anything outside of the Azure DevOps universe. We only use the Azure DevOps SDKs and components based on the their website https://developer.microsoft.com/en-us/azure-devops/

The extension is also opensource, therefore, you are free to fork it and change, review, customize what you need. None of the changes in our official repo accepts external integrations and so far we don't have any feature in mind to have it besides using the native features/sdk of Azure DevOps.

:-)
