### ISSUE TITLE
Error when loading pull request manager hub

### ISSUE THREAD

**Issue by rrodrigues123** [cribeiro84/azure-devops-pull-request-hub#95]
Hi,

when i try to access to the pull request manager hub page i get this "empty" page.
![image](https://user-images.githubusercontent.com/47327500/78785180-93d19100-799e-11ea-839a-a37b27b93d29.png)

At first i thought it was permissions of my user. When it starts loading it appears the normal page.. and then all disapears.

I checked devTools and found some errors:

react-dom.production.min.js:198 TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:68)
    at U (DropdownExpandableButton.js:11)
    at Xo (react-dom.production.min.js:150)
    at Di (react-dom.production.min.js:178)
    at Ga (react-dom.production.min.js:232)
    at $a (react-dom.production.min.js:233)
    at Ns (react-dom.production.min.js:249)
    at Os (react-dom.production.min.js:248)
    at Cs (react-dom.production.min.js:245)
    at es (react-dom.production.min.js:243)
  | da | @ | react-dom.production.min.js:198
-- | -- | -- | --
  | n.callback | @ | react-dom.production.min.js:210
  | oa | @ | react-dom.production.min.js:193
  | ra | @ | react-dom.production.min.js:193
  | Ba | @ | react-dom.production.min.js:217
  | Ha | @ | react-dom.production.min.js:220
  | (anonymous) | @ | react-dom.production.min.js:250
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:18
  | Ds | @ | react-dom.production.min.js:250
  | Ns | @ | react-dom.production.min.js:249
  | Os | @ | react-dom.production.min.js:248
  | Cs | @ | react-dom.production.min.js:245
  | es | @ | react-dom.production.min.js:243
  | enqueueSetState | @ | react-dom.production.min.js:130
  | x.setState | @ | react.production.min.js:13
  | value | @ | PullRequestsTab.tsx:387
  | (anonymous) | @ | PullRequestsTab.tsx:339
  | Promise.finally (async) |   |  
  | (anonymous) | @ | PullRequestsTab.tsx:323
  | l | @ | runtime.js:45
  | (anonymous) | @ | runtime.js:271
  | I.forEach.e.<computed> | @ | runtime.js:97
  | l | @ | runtime.js:45
  | t | @ | runtime.js:135
  | (anonymous) | @ | runtime.js:170
  | i | @ | runtime.js:169
  | E._invoke | @ | runtime.js:192
  | I.forEach.e.<computed> | @ | runtime.js:97
  | e.async | @ | runtime.js:216
  | value | @ | PullRequestsTab.tsx:70
  | (anonymous) | @ | PullRequestsTab.tsx:171
  | Promise.then (async) |   |  
  | (anonymous) | @ | PullRequestsTab.tsx:170

and

DropdownFilterBarItem.js:68 Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:68)
    at U (DropdownExpandableButton.js:11)
    at Xo (react-dom.production.min.js:150)
    at Di (react-dom.production.min.js:178)
    at Ga (react-dom.production.min.js:232)
    at $a (react-dom.production.min.js:233)
    at Ns (react-dom.production.min.js:249)
    at Os (react-dom.production.min.js:248)
    at Cs (react-dom.production.min.js:245)
    at es (react-dom.production.min.js:243)
  | n.renderSelectedItems | @ | DropdownFilterBarItem.js:68
-- | -- | -- | --
  | U | @ | DropdownExpandableButton.js:11
  | Xo | @ | react-dom.production.min.js:150
  | Di | @ | react-dom.production.min.js:178
  | Ga | @ | react-dom.production.min.js:232
  | $a | @ | react-dom.production.min.js:233
  | Ns | @ | react-dom.production.min.js:249
  | Os | @ | react-dom.production.min.js:248
  | Cs | @ | react-dom.production.min.js:245
  | es | @ | react-dom.production.min.js:243
  | enqueueSetState | @ | react-dom.production.min.js:130
  | x.setState | @ | react.production.min.js:13
  | value | @ | PullRequestsTab.tsx:387
  | (anonymous) | @ | PullRequestsTab.tsx:339
  | Promise.finally (async) |   |  
  | (anonymous) | @ | PullRequestsTab.tsx:323
  | l | @ | runtime.js:45
  | (anonymous) | @ | runtime.js:271
  | I.forEach.e.<computed> | @ | runtime.js:97
  | l | @ | runtime.js:45
  | t | @ | runtime.js:135
  | (anonymous) | @ | runtime.js:170
  | i | @ | runtime.js:169
  | E._invoke | @ | runtime.js:192
  | I.forEach.e.<computed> | @ | runtime.js:97
  | e.async | @ | runtime.js:216
  | value | @ | PullRequestsTab.tsx:70
  | (anonymous) | @ | PullRequestsTab.tsx:171
  | Promise.then (async) |   |  
  | (anonymous) | @ | PullRequestsTab.tsx:170

We are using this version:
Installed version
1.20200213.1 (Latest)
Last updated
17/02/2020 at 16:48 WET

Cheers,
Ricardo Rodrigues

**Comment by raoranjeet** [comment]
I can confirm the same behavior. Tried with different browsers too with no luck, page remains blank.

**Comment by raoranjeet** [comment]
Wondering if the issue is related to the number of repos in the team project?  When using a team project with a handful of repos I do not have this issue.  But there is a team project that I spend most time on and it currently has 122 repos and in that the hub fails to load as explained above.  @rrodrigues123 can you confirm if your team project has large number of repos also?  @cribeiro84 any thoughts on this one?

**Comment by rrodrigues123** [comment]
@raoranjeet true story!
I removed myself from a bunch of projects that i still was project admin (it's normaly me who creates the team projects) by default.
So i would say its the teams you are affected in the projects that generate this behavior, not the large list of projects itself.
Thanks!

**Comment by rrodrigues123** [comment]
Hm... bad news. Same behavior. Don't know why it didnt got the same error on my last try. 
So, back to the start. But @raoranjeet other users on my department are using the same collection that has that large list of team projects and they don't have this error. That's why i thought it was about me and my permissions.
Right now i'm in 48 teams in all of the team projects of this collection.

**Comment by cribeiro84** [comment]
@raoranjeet and @rrodrigues123 sorry for the delay in replying back to you - having a little baby does not make my life easier :-)

To be honest, I'm not aware of any additional filter to only capture the repos you are supposed to have access to. The extension simply uses the default "get" repositories from the existing ADO SKD. 

@rrodrigues123 is there any additional info you could share with us? I'm curious because you are getting error when the extension tries to get the text property of the selected item(s). Have you tried to access the extension from any other project that you are admin?

**Comment by cribeiro84** [comment]
Hello @rrodrigues123 and @raoranjeet 
Are you still facing issues with the extension? 

Thanks a lot

**Comment by raoranjeet** [comment]
@cribeiro84  not anymore.  The extension started working for me a few weeks ago.  Whatever you did, fixed it.  Thank you!
