### ISSUE TITLE
There was an error during the extension load: TFS.WebApi.Exception: TF401027

### ISSUE THREAD

**Issue by SeanSteefel** [cribeiro84/azure-devops-pull-request-hub#96]
Full Error:

There was an error during the extension load: TFS.WebApi.Exception: TF401027: You need the Git 'GenericRead' permission to perform this action. Details: identity '{TENANTID-REDACTED}/{USERID-REDACTED}.com', scope 'repository'.

I have reviewed permissions for my account on this ADO instance and I have those permissions - the one bit is we have some repositories that are set to allow nobody access as they are archived and soon-to-be-deleted..  Could the extension not know to ignore repos not permitted access to?

**Comment by SeanSteefel** [comment]
An update.... it seems that if the default repo for a project is restricted then this extension will fail with the above error exception.

**Request:**
Set the code to allow selection of other repo's to still be searchable instead of dying because of a single restricted repo.

**Comment by cribeiro84** [comment]
@SeanSteefel thanks for sharing the details and raising the issue! I will work on a better exception handling process for the extension to avoid this unexpected behavior.

**Comment by cribeiro84** [comment]
Hello @SeanSteefel - is this issue still happening?

**Comment by SeanSteefel** [comment]
It still gets a error 500 but appears to move on to the next so - I would say working now :)

**Comment by cribeiro84** [comment]
Nice! If you could show the error that still happening and I can try to troubleshoot. However, I'm happy it's now working fine again.
