### ISSUE TITLE
Do not count deleted comments

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#98]
1. Create PR
2. Add 2 comments
3. Delete them without resolving
4. Add another comment and resolve
5. On the list of PRs you will see 1/2, however, there's actually one comment.

**Comment by cribeiro84** [comment]
Thanks for raising this issue and we will work on its resolution as soon as possible. Also feel free to raise PRs to help to improve this extension to everyone in case you feel comfortable :-)
