### ISSUE TITLE
Invalid color for the policies icon

### ISSUE THREAD

**Issue by vladkasianenko** [cribeiro84/azure-devops-pull-request-hub#99]
![image](https://user-images.githubusercontent.com/14053728/82910718-a49c8d00-9f73-11ea-8195-91bf78986174.png)
Shouldn't it be red?

**Comment by vladkasianenko** [comment]
And, maybe, instead of "Build success" it should be "Build succeeded."

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/83606691-b5a45a00-a582-11ea-8cc5-168113fadcf9.png)
Here's one more error. It should be green, I guess.

**Comment by vladkasianenko** [comment]
There's also this one:
![image](https://user-images.githubusercontent.com/14053728/83618209-cd83da00-a592-11ea-8109-ed9e9241a5d1.png)
And here's a dashboard:
![image](https://user-images.githubusercontent.com/14053728/83618331-ff953c00-a592-11ea-876d-6417f08192a0.png)

As you can see, there's a message about Build Sucess (red), however, the build is actually fine.

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/83621805-d3c88500-a597-11ea-83ae-51ecd104241b.png)

Also, there's states that this PR is ready to complete (green pictogram), but it can't.

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/86483288-678a9e00-bd5c-11ea-8a6e-b91a6ae4f81f.png)
Invalid counter.

**Comment by vladkasianenko** [comment]
@cribeiro84, any plans for this?

**Comment by cribeiro84** [comment]
This issue has been fixed in the last version. Would you mind to check from your side?

**Comment by vladkasianenko** [comment]
![image](https://user-images.githubusercontent.com/14053728/86582729-c897b900-bf8a-11ea-8776-e301ee2f3125.png)
I guess it should be "Build succeeded" and the red "x" as "failed". So "x - Build succeeded". Does it make any sense, @cribeiro84?
